version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: libc
    versions:
    - 0.2.85
    - 0.2.87
    - 0.2.89
    - 0.2.90
    - 0.2.91
    - 0.2.92
    - 0.2.93
  - dependency-name: js-sys
    versions:
    - 0.3.47
    - 0.3.49
  - dependency-name: wasm-bindgen
    versions:
    - 0.2.72
  - dependency-name: standback
    versions:
    - 0.2.15
    - 0.2.16
  - dependency-name: mio
    versions:
    - 0.7.10
    - 0.7.8
    - 0.7.9
  - dependency-name: regex-syntax
    versions:
    - 0.6.23
  - dependency-name: regex
    versions:
    - 1.4.4
  - dependency-name: lettre
    versions:
    - 0.10.0-beta.2
  - dependency-name: syn
    versions:
    - 1.0.60
    - 1.0.63
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.1.1
    - 1.3.0
  - dependency-name: tokio-util
    versions:
    - 0.6.3
    - 0.6.4
  - dependency-name: async-trait
    versions:
    - 0.1.48
  - dependency-name: security-framework
    versions:
    - 2.1.1
    - 2.1.2
  - dependency-name: pear
    versions:
    - 0.2.2
  - dependency-name: pear_codegen
    versions:
    - 0.2.2
  - dependency-name: bitvec
    versions:
    - 0.19.5
  - dependency-name: tinytemplate
    versions:
    - 1.2.1
  - dependency-name: once_cell
    versions:
    - 1.6.0
    - 1.7.1
    - 1.7.2
  - dependency-name: uncased
    versions:
    - 0.9.5
  - dependency-name: pin-project-lite
    versions:
    - 0.2.5
  - dependency-name: crossbeam-utils
    versions:
    - 0.8.3
  - dependency-name: security-framework-sys
    versions:
    - 2.1.1
  - dependency-name: crossbeam-epoch
    versions:
    - 0.9.3
  - dependency-name: serde_json
    versions:
    - 1.0.63
  - dependency-name: futures
    versions:
    - 0.3.13
  - dependency-name: futures-core
    versions:
    - 0.3.13
  - dependency-name: futures-task
    versions:
    - 0.3.13
  - dependency-name: futures-io
    versions:
    - 0.3.13
  - dependency-name: futures-sink
    versions:
    - 0.3.13
  - dependency-name: futures-channel
    versions:
    - 0.3.13
  - dependency-name: tracing
    versions:
    - 0.1.23
    - 0.1.24
  - dependency-name: idna
    versions:
    - 0.2.1
    - 0.2.2
  - dependency-name: tracing-futures
    versions:
    - 0.2.5
  - dependency-name: parking_lot_core
    versions:
    - 0.8.3
  - dependency-name: funty
    versions:
    - 1.2.0
  - dependency-name: nom
    versions:
    - 6.1.0
    - 6.1.2
  - dependency-name: tap
    versions:
    - 1.0.1
  - dependency-name: figment
    versions:
    - 0.10.3
  - dependency-name: quote
    versions:
    - 1.0.9
  - dependency-name: bstr
    versions:
    - 0.2.15
  - dependency-name: httparse
    versions:
    - 1.3.5
  - dependency-name: ring
    versions:
    - 0.16.20
  - dependency-name: bumpalo
    versions:
    - 3.5.0
    - 3.6.0
  - dependency-name: chunked_transfer
    versions:
    - 1.4.0
  - dependency-name: rand
    versions:
    - 0.8.3
  - dependency-name: serde
    versions:
    - 1.0.123
  - dependency-name: tower-service
    versions:
    - 0.3.1
  - dependency-name: thread_local
    versions:
    - 1.1.2
  - dependency-name: criterion
    versions:
    - 0.3.4
