[package]
name = "rs_bom"
version = "0.1.0"
authors = ["Ephraim Kunz <ephraimkunz@me.com>"]
edition = "2018"

[lib]
name = "rs_bom"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/bin.rs"

[dependencies]
thiserror = "1.0"
lazy_static = "1.4"
regex = "1.3"
anyhow = "1.0"
